# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dist_numpy_attribute_store.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ndarray_pb2 as ndarray__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dist_numpy_attribute_store.proto',
  package='graph2tensor.client',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n dist_numpy_attribute_store.proto\x12\x13graph2tensor.client\x1a\rndarray.proto\"\x96\x01\n\tAttrProto\x12\x38\n\x05\x61ttrs\x18\x01 \x03(\x0b\x32).graph2tensor.client.AttrProto.AttrsEntry\x1aO\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.graph2tensor.client.NdarrayProto:\x02\x38\x01\"/\n\x0b\x41ttrRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x32\xc2\x01\n\x17\x44istNumpyAttributeStore\x12M\n\x06lookup\x12!.graph2tensor.client.NdarrayProto\x1a\x1e.graph2tensor.client.AttrProto\"\x00\x12X\n\rget_attr_data\x12 .graph2tensor.client.AttrRequest\x1a!.graph2tensor.client.NdarrayProto\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[ndarray__pb2.DESCRIPTOR,])




_ATTRPROTO_ATTRSENTRY = _descriptor.Descriptor(
  name='AttrsEntry',
  full_name='graph2tensor.client.AttrProto.AttrsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='graph2tensor.client.AttrProto.AttrsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='graph2tensor.client.AttrProto.AttrsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=223,
)

_ATTRPROTO = _descriptor.Descriptor(
  name='AttrProto',
  full_name='graph2tensor.client.AttrProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='attrs', full_name='graph2tensor.client.AttrProto.attrs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ATTRPROTO_ATTRSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=223,
)


_ATTRREQUEST = _descriptor.Descriptor(
  name='AttrRequest',
  full_name='graph2tensor.client.AttrRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='graph2tensor.client.AttrRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='graph2tensor.client.AttrRequest.batch_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=272,
)

_ATTRPROTO_ATTRSENTRY.fields_by_name['value'].message_type = ndarray__pb2._NDARRAYPROTO
_ATTRPROTO_ATTRSENTRY.containing_type = _ATTRPROTO
_ATTRPROTO.fields_by_name['attrs'].message_type = _ATTRPROTO_ATTRSENTRY
DESCRIPTOR.message_types_by_name['AttrProto'] = _ATTRPROTO
DESCRIPTOR.message_types_by_name['AttrRequest'] = _ATTRREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AttrProto = _reflection.GeneratedProtocolMessageType('AttrProto', (_message.Message,), {

  'AttrsEntry' : _reflection.GeneratedProtocolMessageType('AttrsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ATTRPROTO_ATTRSENTRY,
    '__module__' : 'dist_numpy_attribute_store_pb2'
    # @@protoc_insertion_point(class_scope:graph2tensor.client.AttrProto.AttrsEntry)
    })
  ,
  'DESCRIPTOR' : _ATTRPROTO,
  '__module__' : 'dist_numpy_attribute_store_pb2'
  # @@protoc_insertion_point(class_scope:graph2tensor.client.AttrProto)
  })
_sym_db.RegisterMessage(AttrProto)
_sym_db.RegisterMessage(AttrProto.AttrsEntry)

AttrRequest = _reflection.GeneratedProtocolMessageType('AttrRequest', (_message.Message,), {
  'DESCRIPTOR' : _ATTRREQUEST,
  '__module__' : 'dist_numpy_attribute_store_pb2'
  # @@protoc_insertion_point(class_scope:graph2tensor.client.AttrRequest)
  })
_sym_db.RegisterMessage(AttrRequest)


_ATTRPROTO_ATTRSENTRY._options = None

_DISTNUMPYATTRIBUTESTORE = _descriptor.ServiceDescriptor(
  name='DistNumpyAttributeStore',
  full_name='graph2tensor.client.DistNumpyAttributeStore',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=275,
  serialized_end=469,
  methods=[
  _descriptor.MethodDescriptor(
    name='lookup',
    full_name='graph2tensor.client.DistNumpyAttributeStore.lookup',
    index=0,
    containing_service=None,
    input_type=ndarray__pb2._NDARRAYPROTO,
    output_type=_ATTRPROTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_attr_data',
    full_name='graph2tensor.client.DistNumpyAttributeStore.get_attr_data',
    index=1,
    containing_service=None,
    input_type=_ATTRREQUEST,
    output_type=ndarray__pb2._NDARRAYPROTO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISTNUMPYATTRIBUTESTORE)

DESCRIPTOR.services_by_name['DistNumpyAttributeStore'] = _DISTNUMPYATTRIBUTESTORE

# @@protoc_insertion_point(module_scope)
