# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dist_numpy_attribute_store_pb2 as dist__numpy__attribute__store__pb2
import ndarray_pb2 as ndarray__pb2


class DistNumpyAttributeStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.lookup = channel.unary_unary(
                '/graph2tensor.client.DistNumpyAttributeStore/lookup',
                request_serializer=ndarray__pb2.NdarrayProto.SerializeToString,
                response_deserializer=dist__numpy__attribute__store__pb2.AttrProto.FromString,
                )
        self.get_attr_data = channel.unary_stream(
                '/graph2tensor.client.DistNumpyAttributeStore/get_attr_data',
                request_serializer=dist__numpy__attribute__store__pb2.AttrRequest.SerializeToString,
                response_deserializer=ndarray__pb2.NdarrayProto.FromString,
                )


class DistNumpyAttributeStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def lookup(self, request, context):
        """lookup attributes of nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_attr_data(self, request, context):
        """get all the attribute data of nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistNumpyAttributeStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.lookup,
                    request_deserializer=ndarray__pb2.NdarrayProto.FromString,
                    response_serializer=dist__numpy__attribute__store__pb2.AttrProto.SerializeToString,
            ),
            'get_attr_data': grpc.unary_stream_rpc_method_handler(
                    servicer.get_attr_data,
                    request_deserializer=dist__numpy__attribute__store__pb2.AttrRequest.FromString,
                    response_serializer=ndarray__pb2.NdarrayProto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'graph2tensor.client.DistNumpyAttributeStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DistNumpyAttributeStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/graph2tensor.client.DistNumpyAttributeStore/lookup',
            ndarray__pb2.NdarrayProto.SerializeToString,
            dist__numpy__attribute__store__pb2.AttrProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_attr_data(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/graph2tensor.client.DistNumpyAttributeStore/get_attr_data',
            dist__numpy__attribute__store__pb2.AttrRequest.SerializeToString,
            ndarray__pb2.NdarrayProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
